services:
  jenkins:
    restart: unless-stopped
    build: .
    image: jenkins-ansible:latest
    container_name: jenkins-ansible
    volumes:
      - ./jenkins-home:/var/lib/jenkins:rw
      - ./ansible:/etc/ansible:rw
      - ./site-data:/site-data:rw
      - ./backup:/backup:rw
    ports:
      - 8082:8080
    networks:
      - shared

networks:
  shared:
    driver: bridge
